version: '3'

services:

  app:
    build:
      context: ./app
      dockerfile: ./node.dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: ./nginx.dockerfile
    container_name: nginx
    restart: always
    ports:
     - "8080:80"
    depends_on:
     - app

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root